# Generated by Django 4.1.5 on 2023-02-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
            ],
        ),
    ]
