# Generated by Django 4.1.5 on 2023-02-02 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_remove_commentmodel_total_comments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0004_alter_taskmodel_created_by_id'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votemodel',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.commentmodel'),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='created_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votemodel',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.taskmodel'),
        ),
    ]
