# Generated by Django 4.1.5 on 2023-02-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('assigned_to', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('IAC', 'Inactive'), ('DEL', 'Deleted')], default='AC', max_length=3)),
                ('created_by_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.IntegerField()),
            ],
        ),
    ]
