# Generated by Django 4.1.5 on 2023-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_taskmodel_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
