# Generated by Django 4.1.5 on 2023-02-02 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_taskmodel_total_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
