# Generated by Django 4.1.5 on 2023-02-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_taskmodel_created_by_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'permissions': (('change_taskModel', 'Change taskmodel'),)},
        ),
    ]
