# Generated by Django 4.1.6 on 2023-02-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_userpermissionmodel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'permissions': (('change_task_model', 'Change Taskmodel'),)},
        ),
    ]
