# Generated by Django 4.1.6 on 2023-02-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_alter_votemodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarkmodel',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='userpermissionmodel',
            old_name='created_by_id',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='votemodel',
            old_name='created_by_id',
            new_name='created_by',
        ),
    ]
