# Generated by Django 4.1.6 on 2023-02-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_rename_created_by_id_bookmarkmodel_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostViewedTaskModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
