# Generated by Django 4.1.5 on 2023-02-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermissionModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_id', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to_id', models.IntegerField()),
                ('task_id', models.IntegerField()),
                ('assigned_person', models.CharField(max_length=100)),
                ('permission', models.CharField(choices=[('RO', 'Read Only'), ('ED', 'Edit')], default='RO', max_length=3)),
            ],
        ),
    ]
